server:
  port: 8080

spring:
  datasource:
    # 从环境变量 DB_URL 读取，如果未设置，则使用默认的 aicourse 库
    url: ${DB_URL:jdbc:mysql://localhost:3306/aicourse}
    # 从环境变量 DB_USER 读取，如果未设置，则使用默认的 root
    username: ${DB_USER:root}
    # 从环境变量 DB_PASSWORD 读取，如果未设置，则使用默认的 12345678
    password: ${DB_PASSWORD:12345678}
  data:
    redis:
      # 从环境变量 REDIS_HOST 读取，如果未设置，则使用默认的 localhost
      host: ${REDIS_HOST:localhost}
      port: 6379
  jackson:
    # 配置Jackson处理Java 8时间类型
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 存储配置 (保持不变)
storage:
  type: local
  local-path: upload

# LLM 大语言模型配置
llm:
  dify:
    # 从环境变量 DIFY_API_URL 读取
    api-url: "${DIFY_API_URL:http://219.216.65.193:11434/api}"
    # 从环境变量 DIFY_API_KEY 读取
    api-key: "${DIFY_API_KEY:app-SKDG1Ww8x4Rw4js6WsSuRKYI}"
    model: "deepseek-r1:1.5b"

# 应用专属配置 (新增)
app:
  jwt:
    # 从环境变量 JWT_SECRET 读取，如果未设置，则使用一个默认的、不安全的密钥
    # 生产环境中必须通过环境变量设置一个长且复杂的密钥
    secret: "${JWT_SECRET:your_super_secret_key_for_aicourse_project_which_should_be_long_and_secure}"
    # JWT 过期时间（毫秒），这里是 10 小时
    expiration-ms: 36000000