server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aicourse
    username: root
    password: 12345678
  data:
    redis:
      host: localhost
      port: 6379
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
